version: '3'

services:
  encrypt:
    build: ./NeudaTaskA
    volumes:
      - datavolume: /data:rw

  decrypt:
    build: ./NeudaTaskB
    links:
      - "encrypt"
    depends_on:
      - "encrypt"
    volumes:
      - datavolume: /data:rw

volumes:
  datavolume: {}

