version: '3'

services:
  encrypt:
    build: ./NeudaTaskA
    volumes:
      - type: bind
        source: {%cd%}\json_file.json
        target: ./json_file.json
      - type: volume
        source: datavolume
        target: /outputdata

  decrypt:
    build: ./NeudaTaskB
    depends_on:
      - "encrypt"
    volumes:
      - type: volume
        source: datavolume
        target: /outputdata

#put the named volumes here - this can be shared between containers
#the named volumes are used for sharing generated data
#the bind volume is used for passing in data

volumes:
  datavolume: {}

